--- #YAML:1.0
name: CGI-Upload
version: 1.10
author: Rob Casey <rob.casey@bluebottle.com>
abstract: CGI class for handling browser file uploads
license: perl
requires:
  CGI: 2.47
  Carp: 0
  File::MMagic: 1.16
  HTTP::BrowserDetect: 0.97
  Test::More: 0
provides:
  CGI::Upload:
    file: lib/CGI/Upload.pm
    version: 1.10
generated_by: Module::Build version 0.25
