# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Upload
version:      1.08
version_from: lib/CGI/Upload.pm
installdirs:  site
requires:
    CGI:                           2.47
    File::MMagic:                  1.16
    HTTP::BrowserDetect:           0.97

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
